### PR TITLE
Task4

### PR DESCRIPTION
**Pull request by v0f**
Task: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task4-rds/task.md

What was done?
Task 4.1 is implemented:
https://github.com/v0f/aws-shop-be/blob/task4/create-fill-tables.sql
TASK 4.2 is implemented 
TASK 4.3 is implemented lambda links are provided and products is stored in DB:
   **getProductsById**: https://656aqwnv3i.execute-api.eu-west-1.amazonaws.com/dev/products/e9832b30-2d1d-4e74-9abe-47bd43a6862f
   **getProductsList**: https://656aqwnv3i.execute-api.eu-west-1.amazonaws.com/dev/products/

body example for post request:
`{
    "title": "postTitle",
    "description": "desc",
    "price": 10,
    "img_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/400_degrees_new_england_roast_coffee.png/100px-400_degrees_new_england_roast_coffee.png",
    "count": 5
}`

**Frontend application** is integrated with product service (/products API): https://di4ivpaoki0ld.cloudfront.net/

Additional tasks:
    +1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
    +1 - All lambdas do console.log for each incoming requests and their arguments
    +1 - Transaction based creation of product

### CODE REVIEW

**Comment by ArtiFisher** [comment]
> will commit in an hour :)


@v0f, have you commited(and pushed) everything? Can't see more commits after da46a8b

**Comment by NurbekAman** [comment]
Where is task4? What you did is related to task3

**Comment by NurbekAman** [comment]
according to task 4.1 you should provide sql requests in PR

**Comment by v0f** [comment]
> according to task 4.1 you should provide sql requests in PR

added link to sql file for convenience :)
task 4.1 says just "Store it in your GIT repository"

**Comment by NurbekAman** [comment]
> > according to task 4.1 you should provide sql requests in PR
> 
> added link to sql file for convenience :)
> task 4.1 says just "Store it in your GIT repository
Thanks)

**Pull request merged**
